---
title: "Weekly Summary Report"
date: 'Last updated: `r format(Sys.Date())`'
output:
  html_document:
    dpi: 500
    fig_width: 10
    fig_height: 7
---

```{r, echo=FALSE}

# Insert NFL logo in top right of report
htmltools::img(src = knitr::image_uri("/Users/Stephan/Desktop/R Projects/NFL/NFL.png"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px; width: 110px; height: 128px')

```


```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

Below you'll find figures showing key advanced metrics I'm tracking for all 32 NFL teams.

```{r, echo =FALSE}

library(nflfastR)
library(tidyverse)
library(teamcolors) # NFL team colors and logos
library(extrafont) # for extra fonts
library(ggrepel) # better labels
library(ggimage)
library(glue)
library(ggtext)
library(reactable)
library(reactablefmtr)
library(ggalt) #for dumbbell plot
library(ggforce)
library(ggsci)
library(gtExtras)


# Optional but makes R prefer not to display numbers in scientific notation
options(scipen = 9999)


data <- load_pbp(2021) #Load 2021 PBP data from nflfastR

# Filter for Run/Pass plays for the 2021 season only
pbp_rp <- data %>%
  filter(rush == 1 | pass == 1, !is.na(epa)) # Exclude plays with missing EPA.

# Identify current week
current_week <- max(pbp_rp$week)

```

 
```{r, echo=FALSE}

library(gt)

# Create 538 GT table theme from Thomas Mock's blog.Comes from this post: https://themockup.blog/posts/2020-09-26-functions-and-themes-for-gt-tables/?panelset3=theme-code2&panelset4=theme-code3 
gt_nfl_theme_538 <- function(data,...) {
  data %>%
    # Add team logos w/ web_image
    text_transform(
      locations = cells_body(
        vars(team_logo_espn)
      ),
      fn = function(x) {
        web_image(
          url = x,
          height = 25
        )
      }
    ) %>%
    # Relabel columns
    cols_label(
      team_logo_espn = ""
    ) %>%
    opt_all_caps()  %>%
    opt_table_font(
      font = list(
        google_font("Chivo"),
        default_fonts()
      )
    ) %>%
    tab_style(
      style = cell_borders(
        sides = "bottom", color = "transparent", weight = px(2)
      ),
      locations = cells_body(
        columns = TRUE,
        # This is a relatively sneaky way of changing the bottom border
        # Regardless of data size
        rows = nrow(data$`_data`)
      )
    )  %>% 
    tab_options(
      column_labels.background.color = "white",
      table.border.top.width = px(3),
      table.border.top.color = "transparent",
      table.border.bottom.color = "transparent",
      table.border.bottom.width = px(3),
      column_labels.border.top.width = px(3),
      column_labels.border.top.color = "transparent",
      column_labels.border.bottom.width = px(3),
      column_labels.border.bottom.color = "black",
      data_row.padding = px(3),
      source_notes.font.size = 12,
      table.font.size = 16,
      heading.align = "left",
      ...
    ) 
}

# Define 538 table theme for Reactable table(s) below
theme_538 <- function() {
    reactable::reactableTheme(
        searchInputStyle = list(width = "31%", backgroundColor = "#F9F9F9"),
        style = list(
            fontFamily = "Chivo"
        ),
        headerStyle = list(
            "&:hover[aria-sort]" = list(
                background = "hsl(0, 0%, 80%)"),
            "&[aria-sort='ascending'], &[aria-sort='descending']" = list(
                background = "#555",
                color = "#FFF"
            ),
            borderColor = "#333"
        ),
        borderColor = "#CDCDCD"
    )
}

# Custom ggplot theme (inspired by Owen Phillips at the F5 substack blog)
theme_custom <- function () { 
  theme_minimal(base_size=11, base_family="Chivo") %+replace% 
    theme(
      panel.grid.minor = element_blank(),
      plot.background = element_rect(fill = 'floralwhite', color = "floralwhite")
    )
}

#Define color palette to use in table
my_color_pal <- c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab")

```

***
### Current Standings

```{r}
games_df <- nflreadr::load_schedules() %>% 
  filter(season == 2021, game_type == "REG") %>% 
  select(game_id, team_home = home_team, team_away = away_team, result, week) %>% 
  pivot_longer(contains('team'), names_to = 'home_away', values_to = 'team', names_prefix = 'team_') %>% 
  mutate(
    result = ifelse(home_away == 'home', result, -result),
    win = ifelse(result == 0 , 0.5, ifelse(result > 0, 1, 0))
  ) %>% 
  select(week, team, win, result) %>% 
  drop_na()


team_df <- nflreadr::load_teams() %>% 
  select(team_logo_espn, team_abbr, team_conf, team_division)

joined_df <- games_df %>% 
  group_by(team) %>% 
  summarise(
    Wins = length(win[win==1]),
    Losses = length(win[win==0]),
    result = sum(result),
    outcomes = list(win), .groups = "drop") %>% 
  left_join(team_df, by = c("team" = "team_abbr")) %>% 
  select(team_logo_espn, team_conf, team_division, Wins, Losses, result, outcomes)

# Make AFC table
final_df <- joined_df %>% 
  filter(team_conf == "AFC") %>% 
  group_by(team_division) %>% 
  arrange(desc(Wins)) %>% 
  ungroup() %>% 
  arrange(team_division)

standings_table_afc <- final_df %>% 
 gt(groupname_col = "team_division") %>%
  gt_plt_winloss(outcomes, max_wins = 17) %>% 
  gt_img_rows(columns = team_logo_espn, height = 25) %>% 
  gtExtras::gt_theme_538() %>%
  cols_label(
    team_logo_espn = "Team",
    team_conf = "Conference",
    result = "Point Diff",
  ) %>% 
  cols_align(align = "center",
               columns = 2:6) %>%
  tab_header(title = md("**2021 AFC Standings**"),
               subtitle = glue("Thru Week {current_week} games"))


# Make NFC table
final_df <- joined_df %>% 
  filter(team_conf == "NFC") %>% 
  group_by(team_division) %>% 
  arrange(desc(Wins)) %>% 
  ungroup() %>% 
  arrange(team_division)

standings_table_nfc <- final_df %>% 
 gt(groupname_col = "team_division") %>%
  gt_plt_winloss(outcomes, max_wins = 17) %>% 
  gt_img_rows(columns = team_logo_espn, height = 25) %>% 
  gtExtras::gt_theme_538() %>%
  cols_label(
    team_logo_espn = "Team",
    team_conf = "Conference",
    result = "Point Diff",
  ) %>%
   cols_align(align = "center",
               columns = 2:6) %>%
  tab_header(title = md("**2021 NFC Standings**"),
               subtitle = glue("Thru Week {current_week} games"))


standings_table_afc
standings_table_nfc

```

***
### Current Rankings

Offensive and defensive rankings, according to various advanced metrics. Click a column header to sort by that statistic.

```{r}

offense <- pbp_rp %>%
    group_by(posteam)%>%
    summarize(
        n_pass=sum(pass),
        n_rush=sum(rush),
        epa_per_pass=sum(epa*pass)/n_pass,
        epa_per_rush=sum(epa*rush)/n_rush,
        success_per_pass=sum(pass*epa>0)/n_pass,
        success_per_rush=sum(rush*epa>0)/n_rush,
        off_epa=mean(epa))

defense <- pbp_rp %>%
    group_by(defteam)%>%
    summarize(
        def_n_pass=sum(pass),
        def_n_rush=sum(rush),
        def_epa_per_pass=sum(epa*pass)/def_n_pass,
        def_epa_per_rush=sum(epa*rush)/def_n_rush,
        def_success_per_pass=sum(pass*epa>0)/def_n_pass,
        def_success_per_rush=sum(rush*epa>0)/def_n_rush,
        def_epa=mean(epa)
    )

off_def_epa <- offense %>% 
    inner_join(defense, by=c("posteam" = "defteam")) %>%
    left_join(nflfastR::teams_colors_logos, by = c("posteam" = "team_abbr"))


#Make table using Reactable

off_def_epa2 <- off_def_epa %>% 
    mutate(`Overall EPA` = off_epa - def_epa) %>% 
  select(team_logo_espn, posteam,`Overall EPA`, off_epa, def_epa, epa_per_pass, epa_per_rush, def_epa_per_pass, def_epa_per_rush, success_per_pass, success_per_rush) %>% 
  arrange(desc(`Overall EPA`))


statistics_table <- reactable(
  off_def_epa2,
  theme = theme_538,
                  showSortIcon = TRUE,
                  searchable = TRUE,
                  language = reactableLang(
                      searchPlaceholder = "SEARCH FOR A TEAM..."),
                  defaultPageSize = 100,
                  columns = list(
                      posteam = colDef(name = "Team",
                                       align = "left"),
                      `Overall EPA` = colDef(name = "Overall EPA/Play",
                                       align = "right",
                                       style = color_scales(off_def_epa2, colors = my_color_pal),
                                       format =  colFormat(digits = 2)),
                      off_epa = colDef(name = "Off EPA/Play",
                                       align = "right",
                                       format =  colFormat(digits = 2)),
                      def_epa = colDef(name = "Def EPA/Play",
                                       align = "right",
                                       format =  colFormat(digits = 2)),
                      epa_per_pass = colDef(name = "EPA/Pass",
                                       align = "right",
                                       format =  colFormat(digits = 2)),
                      epa_per_rush = colDef(name = "EPA/Rush",
                                       align = "right",
                                       format =  colFormat(digits = 2)),
                      def_epa_per_pass = colDef(name = "Def EPA/Pass",
                                       align = "right",
                                       format =  colFormat(digits = 2)),
                      def_epa_per_rush = colDef(name = "Def EPA/Rush",
                                       align = "right",
                                       format =  colFormat(digits = 2)),
                      success_per_pass = colDef(name = "Pass SR",
                                       align = "right",
                                       format =  colFormat(percent = TRUE, digits = 1)),
                       success_per_rush = colDef(name = "Rush SR",
                                       align = "right",
                                       format =  colFormat(percent = TRUE, digits = 1)),
                      
                      ### add logos using embed_img()
                      team_logo_espn = colDef(
                          name = "",
                          maxWidth = 70,
                          align = "center",
                          cell = embed_img(height = "25", width = "30")
                      )),
                  pagination = FALSE,
                  compact = TRUE, 
                  borderless = FALSE, 
                  striped = FALSE,
                  fullWidth = FALSE, 
                  defaultColDef = colDef(align = "center", minWidth = 95)
        )

statistics_table

```
