---
title: "Current Week Odds"
date: 'Last updated: `r format(Sys.Date())`'
output:
  html_document:
    dpi: 500
    fig_width: 10
    fig_height: 7
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r, echo=FALSE}

library(nflfastR)
library(nflseedR)
library(htmltools)
library(tidyverse)
library(teamcolors) # NFL team colors and logos
library(extrafont) # for extra fonts
library(ggrepel) # better labels
library(ggimage)
library(glue)
library(ggtext)
library(reactable)
library(reactablefmtr)
library(ggforce)
library(gt)
library(gtExtras)
library(webshot)
library(webshot2)
library(scales)


# Define 538 table theme for Reactable table(s) below
theme_538 <- function() {
    reactable::reactableTheme(
        searchInputStyle = list(width = "31%", backgroundColor = "#F9F9F9"),
        style = list(
            fontFamily = "Titillium Web"
        ),
        headerStyle = list(
            "&:hover[aria-sort]" = list(
                background = "hsl(0, 0%, 80%)"),
            "&[aria-sort='ascending'], &[aria-sort='descending']" = list(
                background = "#555",
                color = "#FFF"
            ),
            borderColor = "#333"
        ),
        borderColor = "#CDCDCD"
    )
}



```


Below you'll find current week game odds based on my simulations of the remainder of the NFL season.

```{r, echo=FALSE}

# Optional but makes R prefer not to display numbers in scientific notation
options(scipen = 9999)

# load team logos and colors
team_df <- nflreadr::load_teams() %>% 
  select(team_logo_espn, team_abbr, team_name, team_conf, team_division, team_color)

#Load games data from Lee Sharpe/nflseedR
# games <- load_sharpe_games() %>% 
#   filter(season == 2024)

# Load games from output of forecast simulations
games <- read_csv('/Users/Stephan/Desktop/R Projects/NFL/Latest Game Predictions.csv')

# Identify current week
#current_week <- max(current_week_games$week)
current_week <- 11

# filter for current week games only
# current_week_games <- games %>%
#   filter(gameday >= Sys.Date())

current_week_games <- games %>%
  filter(current_week == games$week)

# join team logs and colors
current_week_games<- left_join(current_week_games, team_df, by = c("away_team" = "team_abbr")) #Away
current_week_games <- left_join(current_week_games, team_df, by = c("home_team" = "team_abbr")) #Home

# filter for relevant columns
current_week_games2 <- current_week_games %>%
  select(week, game_type, team_logo_espn.x, away_team, team_logo_espn.y, home_team, result, away_percentage, home_percentage) %>% 
  rename(team_logo_espn_away = team_logo_espn.x,
         team_logo_espn_home = team_logo_espn.y) %>%
  # make list for implied odds bar chart
  mutate(list_data = list(c(away_percentage, home_percentage))) %>%
  gather(attr_num, list_data, c(away_percentage, home_percentage)) %>%
  group_by_at(vars(-attr_num, -list_data)) %>%
  summarise(list_data = list(list_data)) %>%
  ungroup()

# Make gt table
current_week_games2 %>%
  select(game_type, week, away_team, team_logo_espn_away, list_data, home_team, team_logo_espn_home, result) %>%
  gt() %>%
  gt_img_rows(team_logo_espn_away, height = 30) %>%
  gt_img_rows(team_logo_espn_home, height = 30) %>%
  # Relabel columns
  cols_label(
    game_type = "Game Type",
    week = "Week",
    away_team = "",
    team_logo_espn_away = "",
    home_team = "",
    team_logo_espn_home = "",
    result = "Predicted Spread"
  ) %>%
  fmt_number(
    columns = vars(result),
    decimals = 1
  ) %>%
  cols_align(
    align = "center",
    columns = vars(week)  # Center align the week column
  ) %>%
  tab_header(
    title = md("**NFL Current Week Odds**"),
    subtitle = glue("2025 Regular Season: Week {current_week}")
  ) %>%
  tab_source_note(
    source_note = md("DATA: nflfastR")
  ) %>%
  gt_plt_bar_stack(list_data,
    width = 60,
    #scale_type = "percent",
    labels = c("  Away  ", "  Home  "),
    palette = c("#ff4343", "#0038A8")
  ) %>%
  tab_footnote(
    footnote = "Win probabilities based on 1,000x simulations of remaining games using Between the Pipes' team power ratings.",
    locations = cells_column_labels(vars(list_data))
  ) %>%
  tab_footnote(
    footnote = "Spread from the perspective of the home team.",
    locations = cells_column_labels(vars(result))
  ) %>%
  opt_table_font(
    font = "Titillium Web"
    ) %>%
  tab_options(
    column_labels.background.color = "white",
    table.border.top.width = px(3),
    table.border.top.color = "transparent",
    table.border.bottom.color = "transparent",
    table.border.bottom.width = px(3),
    column_labels.border.top.width = px(3),
    #column_labels.border.top.color = "transparent",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "black",
    data_row.padding = px(3),
    source_notes.font.size = 12,
    table.font.size = 16,
    heading.align = "center",
    heading.background.color = "black",
  )


```